version: '3.8'

services:
  prysm-validator-account-import:
    image: gcr.io/prysmaticlabs/prysm/validator:stable
    container_name: prysm-validator-account-import
    command: accounts import --keys-dir=/keys --wallet-dir=/data/wallets --wallet-password-file="/data/passwords/wallet-password.txt" --accept-terms-of-use --pyrmont
    networks:
      - testnet
    volumes:
      - $HOME/validator_keys:/keys
      - $HOME/validator:/data

networks:
  testnet:
    name: testnet
